CREATE DATABASE recipes_site;
USE recipes_site;

CREATE TABLE Recipes(
	id INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR( 50 ) NOT NULL,
	description VARCHAR( 255 ) NOT NULL
);

CREATE TABLE Users(
	id INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR( 50 ) NOT NULL,
	email VARCHAR( 50 ) NOT NULL UNIQUE,
	password VARCHAR( 255 ),
	
	UNIQUE( email )
);

CREATE TABLE Favorites(
	id INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_user INT( 11 ) UNSIGNED NOT NULL,
	id_recipe INT( 11 ) UNSIGNED NOT NULL,
	
	FOREIGN KEY( id_user ) REFERENCES Users( id ),
	FOREIGN KEY( id_recipe ) REFERENCES Recipes( id )
);

CREATE TABLE Votes(
	id INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_user INT( 11 ) UNSIGNED NOT NULL,
	id_recipe INT( 11 ) UNSIGNED NOT NULL,
	
	FOREIGN KEY( id_user ) REFERENCES Users( id ),
	FOREIGN KEY( id_recipe ) REFERENCES Recipes( id )
);
